Repository kevinmatthes/aeruginous-rs, pull requests merged in 2024-03, with the labels that each got.

#1261 [Bugfix] CI: Run Coverage Workflow Correctly on Fork Repositories
  .github/workflows/pr.yml
  changelog.d/20240301_184631_GitHub_Actions_pr-coverage.ron
Labels: bug

#1264 [Bugfix] Skip Code Coverage Determination
  .github/workflows/pr.yml
  changelog.d/20240302_193739_GitHub_Actions_skip-code-coverage-determination.ron
Labels: bug

#1260 [Enhancement] CI: Add Manual Trigger for rustfmt Workflow
  .github/workflows/rustfmt.yml
  changelog.d/1238.rst
Labels: enhancement

#1276 [Bugfix] CI: Adjust Code Coverage Workflow
  .github/workflows/pr.yml
  changelog.d/20240308_180820_GitHub_Actions_change-code-coverage-workflow.ron
Labels: bug

#1315 [Documentation] Update MSRV to v1.77.0
  changelog.d/msrv.rst
Labels: documentation

#1341 [Documentation] MSRV 1.77.1
  changelog.d/20240331_171043_GitHub_Actions_msrv-1.77.1.ron
  changelog.d/msrv.rst
Labels: documentation
